name: Deploy React App to cPanel

on:
  push:
    branches:
      - main  # Se ejecutará cada vez que subas cambios a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Obtener el código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Puedes cambiar a la versión exacta que uses

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🏗️ Construir el proyecto
        run: npm run build

      - name: 🚀 Subir a cPanel por SFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_KEY: ${{ secrets.FTP_KEY }}
          FTP_KEY_PASSPHRASE: ${{ secrets.FTP_KEY_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          echo "$FTP_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -p -P "$FTP_KEY_PASSPHRASE" -N "" -f ~/.ssh/id_rsa
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -d -c "set sftp:connect-program 'ssh -a -x -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no'; open -u $FTP_USERNAME, sftp://$FTP_SERVER; mirror -R --parallel=10 build/ public_html/sistema/"
