name: Deploy React App to cPanel

on:
  push:
    branches:
      - main  # Se ejecutará cada vez que subas cambios a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Obtener el código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Puedes cambiar a la versión exacta que uses

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🏗️ Construir el proyecto
        run: npm run build

      - name: 🚀 Subir a cPanel por SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.FTP_KEY }}
          passphrase: ${{ secrets.FTP_KEY_PASSPHRASE }}
          port: 22
          source: "build/*"
          target: "/home/stenergyedu/public_html/sistema/"
          strip_components: 1
